var questions = [

    // Grundlagen I:
    "Zeichnen Sie die Wissenspyramide und erklären Sie ihre einzelnen Elemente.",
    "Wie viele Symbole in Folge werden benötigt um 8 Zeichen zu codieren?",
    "Was ist ein Transistor?",
    "Was ist die kleinste mögliche Einheit der Information?",
    "Erläutern Sie Signifikat und Signifikant.",
    "Beschreiben Sie die Wissenspyramide",
    "Definieren Sie die beiden Begriffe Signifikat und Signifikant",
    "Wie ist ein Binärbaum aufgebaut?",
    "Was ist ein Wiegendruck?",
    "Was bezeichnet der Begriff \"Semiotik\"?",
    "Was bezeichnet der Begriff \"Semantik\"?",
    "Was bezeichnet der Begriff \"Pragmatik\"?",
    "Was bezeichnet der Begriff \"Information\"?",
    "Was bezeichnet der Begriff \"Daten\"?",

    // Grundlagen II:
    "Was ist der ASCII-Code?",
    "Stellen Sie drei unterschiedliche Zahlensysteme gegenüber.",
    "Wandeln Sie 3056 vom Dezimal- ins Hexadezimalsystem um.",
    "Wandeln Sie die Binärzahl 1001 in ihre dezimale Entsprechung um",
    "Wie wurde der ASCII-Code erweitert und welchen Nutzen hat diese Erweiterung?",
    "Welche Zahlensysteme kennen Sie?",
    "Welche 4 Zahlensysteme haben Sie in der Vorlesung kennengelernt? Welche Zahlenbereiche beinhalten die einzelnen Systeme?",
    "Wandeln sie die folgende Zahl des Binärsystems ins Dezimalsystem um: 11000",
    "Wandeln Sie die folgende Zahl des Dezimalsystems ins Binärsystem um: 126",
    "Welche Grenzen hat der ASCII-Code?",
    "Was ist UTF-8?",
    "Wie sieht das Hexadezimalsystem aus?",
    "Wie sieht 296 im Binärcode aus?",
    "Welche Zahl entspricht 10011101 als Dezimalzahl?",
    "Warum gibt es UTF-8?",
    "Was ist mit ISO-8859-n bezeichnet?",

    // Grundlagen III:
    "Addieren Sie unter Beachtung der Additionsregeln die folgenden beiden Binärzahlen miteinander: 1101 1100 + 0101 0101",
    "Fassen Sie die Vorgehensweise der Multiplikation im Binärsystem kurz zusammen",
    "Addieren sie 5 und 30 im Binärsystem.",
    "Addieren Sie 40, 25, 7 und 10 im Binärsystem.",
    "Multiplizieren Sie die Dezimalzahlen 13 und 5 im Binärsystem",
    "Was ist ein Nibble?",
    "Was ist ein Byte?",
    "Addieren Sie: 1001 1110 + 0101 1111",
    "Addieren Sie: 1111 1111 + 0000 0001",
    "Berechnen Sie im Binärsystem: -7+11",
    "Berechnen Sie im Binärsystem:  100-20",
    "Wie lautet die Dezimalzahl 47 Binär?",
    "Wie lautet die Dezimalzahl 46703 Hexadezimal?",
    "Addiere 1011 0101 mit 1000 1011.",
    "Was ist das Produkt von 1110 und 1010?",
    "Was ist die Zweierkomplementärdarstellung?",
    "Welche zwei Zahlen entspricht 0101?",
    "Aus wie vielen Bit besteht ein Byte?",

        // Grundlagen IV:
    "Welches Problem tritt auf wenn man negative Zahlen mit Hilfe des MSB darstellt?",
    "Wie viel Byte haben 32 Bit?",
    "Wie lassen sich negative Zahlen Binär darstellen? Nennen Sie zwei Möglichkeiten.",
    "Bilden Sie das Zweierkomplement von 15.",
    "Berechnen Sie 10 minus 15.",
    "Berechnen Sie 12 minus 6.",
    "Wie wird im Binärsystem Subtrahiert?",
    "Berechnen Sie im Binärsystem unter Verwendung des Zweierkompliments: 21-9",
    "Berechnen Sie im Binärsystem unter Verwendung des Zweierkompliments: 5-11",
    "Wofür steht MSB?",
    "Wofür steht LSB?",


    // Rechnertechnologie I:
    "Was ist der Turingtest?",
    "Beschreiben Sie den Von-Neumann-Zyklus.",
    "Benennen Sie die 5 Teilschritte des Von-Neumann-Zyklus",
    "Was sind die Eigenschaften der Von-Neumann-Architektur?",
    "Wie ist die Von-Neumann-Architektur aufgebaut?",
    "Erklären Sie den Minimax-Algorithmus.",
    "Was entwickelten von Neumann und Morgenstern?",
    "Wofür steht die Abkürzung \"CPU\"?",
    "Wofür steht die Abkürzung \"GPU\"?",
    "Wofür steht die Abkürzung \"RAM\"?",
    "Was ist der Integrationsgrad?",
    "Was war die Spieltheorie nach von Neumann und Morgenstern?",
    "Welche Problematik beschreibt das Gefangenendilemma?",
    "Wie hieß eine erste Implementierung des Turingtests?",
    "Geben Sie das Mooresche Gesetz wieder!",
    "Was leistete Alan Turing im 2. Weltkrieg?"

];